### PR TITLE
Updated UI, added favicon, removed bug from settings.py

### PR DESCRIPTION
**Pull request by haseeb-555**
---

### Pull Request Description

**Objective**  
The frontend of the application previously lacked CSS and proper styling, negatively impacting the user experience. This PR enhances the user interface by implementing appropriate CSS and ensuring responsiveness.

### Features Implemented
1. **Dark and Light Theme**: Implemented both dark and light themes, allowing users to choose their preferred visual experience.
2. **Scrollable Footer**: Added a scrollable footer for consistent navigation and information throughout the application.
3. **Responsive Design**: Ensured that the styling is responsive across different screen sizes for a seamless user experience on all devices.
4. **Favicon**: Implemented a favicon to improve brand recognition and provide a polished appearance in the browser tab.
5. **CSS**: Added comprehensive CSS styles to improve the overall appearance of the application.
6. **Bug Fix in `settings.py`**: Resolved an issue in `settings.py` to enhance application functionality.

### Expected Outcome
The application now features a visually appealing and responsive design, complete with a well-structured scrollable footer, a favicon, dark and light themes, and improved functionality, resulting in an enhanced user experience.

---

Screenshot 2024-10-13 115459

Screenshot 2024-10-13 122013

Let me know if you need any further adjustments.

### CODE REVIEW

**Comment by Nandika-A** [comment]
@haseeb-555 Revert settings.py, it was perfectly fine. Avoid making changes in such files.

**Comment by haseeb-555** [comment]
> @haseeb-555 Revert settings.py, it was perfectly fine. Avoid making changes in such files.
 It was not running when i ran on my machine saying it has to be 'none' instead of 'None' so i have to change that  line
but now i have just kept the same code as u mentioned

**Comment by Nandika-A** [comment]
> > @haseeb-555 Revert settings.py, it was perfectly fine. Avoid making changes in such files.
> 
> but it was not running when i ran on my machine saying it has to be 'none' instead of 'None' so i have change that single line

Did you create a .env?

**Comment by haseeb-555** [comment]
> > > @haseeb-555 Revert settings.py, it was perfectly fine. Avoid making changes in such files.
> > 
> > 
> > but it was not running when i ran on my machine saying it has to be 'none' instead of 'None' so i have change that single line
> 
> Did you create a .env?

YES

**Comment by haseeb-555** [comment]
> > > @haseeb-555 Revert settings.py, it was perfectly fine. Avoid making changes in such files.
> > 
> > 
> > but it was not running when i ran on my machine saying it has to be 'none' instead of 'None' so i have change that single line
> 
> Did you create a .env?

does the webstite working cause im unable to open it and i should submit my pr link in it

**Comment by Nandika-A** [comment]
> > > > @haseeb-555 Revert settings.py, it was perfectly fine. Avoid making changes in such files.
> > > 
> > > 
> > > but it was not running when i ran on my machine saying it has to be 'none' instead of 'None' so i have change that single line
> > 
> > 
> > Did you create a .env?
> 
> does the webstite working cause im unable to open it and i should submit my pr link in it

The server seems down

**Review by Nandika-A — APPROVED** [review]
LGTM

**Comment by Nandika-A** [comment]
@haseeb-555 Raise the PR on contrihub's site, not on my personal account.

**Pull request closed without merging**
